<?php
include '../config.php';
include('includes/header.php'); 
include('includes/navbar.php'); 
?>


<!-- Content Header (Page header) -->
<div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Print Invoice</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="index.php">Dashboard</a></li>
                        <li class="breadcrumb-item active">Invoice</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <div class="container-fluid">
<div class="row">

<!-- Earnings (Monthly) Card Example -->
<div class="col-xl-12 col-md-6 mb-4">
  <div class="card border-left-primary shadow h-100 py-2">
    <div class="card-body">
      <div class="row no-gutters align-items-center">
        <div class="col mr-2">

        <?php

          $id = $_GET['id'];

          $query = "SELECT * FROM reservation where id='$id'";
          $query_run = mysqli_query($conn, $query);
              
        ?>
        <div  id="table">
        <table class="table table-hover">
          <thead>
            <th scope="col">Reservation ID</th>
            <th scope="col">Customer ID</th>
            <th scope="col">Rooms</th>
            <th scope="col">Check in date</th>
            <th scope="col">Check out date</th>
            <th scope="col">Amount</th>
          </thead>

        <?php
          if($query_run)
          {
            foreach($query_run as $row)
            {
        ?>
        
          <tbody>
            <td><?php echo $row['id'];?></td>
            <td><?php echo $row['cuss_id'];?></td>
            <td><?php echo $row['rooms'];?></td>
            <td><?php echo $row['check_in'];?></td>
            <td><?php echo $row['check_out'];?></td>
            <td><?php echo $row['total'];?></td>
            
          </tbody>


        <?php

            }
          }
          else
          {
            echo "no fines";
          }

        ?>
        </table>
        </div>

        <button name="submit" class="btn btn-primary print">Print Invoice</button>

        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>

<script src="js/jquery.min.js"></script>
<script>
  $('.print').click(function(){
        var date = new Date().toJSON().slice(0,10).replace(/-/g,'/');
        var hedding = "<center><h3 style='color:#4e73df;'>LakDerana Hotels</h3></center>";
        var topic = "<h5>Payment Invoice "+  date  +"</h5>";
        var bottom = "Report generated by: <?php echo $_SESSION['id']; ?>"
        var divElements = document.getElementById("table").innerHTML;
        var oldPage = document.body.innerHTML;
        document.body.innerHTML = hedding + topic + divElements + bottom;
        window.print();
        document.body.innerHTML = oldPage;
  })
</script>
 



<?php
include('includes/scripts.php');
include('includes/footer.php');
?>